site_name: Citrix Provisioning 1909 SOAP Server Programmer's Guide
site_description: Programmer's Guide for Citrix Provisioning 1909 SOAP Server
site_title: Developer Docs
site_url: https://developer-docs.citrix.com/

# Copyright
copyright: '&copy; 1999-2021 Citrix Systems, Inc. All rights reserved. '

# Feedback

issues_uri: https://github.com/citrix/devdocs-issue-collector/issues/new
assignees_uri:
  - kurtcoll
labels_uri:
  - documentation

extra_css:
  - 'assets/stylesheets/extra.css'
  - https://use.fontawesome.com/releases/v5.12.1/css/all.css

# Configuration
theme:
  name: null
  custom_dir: devdocs-theme
  
  # 404 page
  static_templates:
    - 404.html
  
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  
  # Default values, taken from mkdocs_theme.yml
  language: en

  palette:
    primary: teal
    accent: teal
  font: false
  favicon: https://docs.citrix.com/assets/images/favicon.ico
  logo: https://developer-docs.citrix.com/_static/logo.svg
  icon: fontawesome

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCiOupk9QF6jdk3EDKTHDykA
    - icon: fontawesome/brands/github-alt
      link: https://github.com/citrix
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/citrixdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/citrix/

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
  - search:
      separator: '[\s\-\.]+'
      prebuild_index: true

nav:
- Versions:
  - latest: https://developer-docs.citrix.com/projects/provisioning-services-sdk/en/latest/
  - 1912: https://developer-docs.citrix.com/projects/provisioning-services-sdk/en/1912/
- Introduction: index.md
- Short command list: short-command-list.md
- Commands by object type: commands-by-object-type.md
- MapiReturn returnCode and exceptionType: mapireturn.md
- Questions?: https://discussions.citrix.com/forum/1385-citrix-developer-exchange/