site_name: Citrix Provisioning 2003 SOAP Server Programmer's Guide
site_description: Programmer's Guide for Citrix Provisioning 2003 SOAP Server
site_title: Developer Docs
site_url: https://developer-docs.citrix.com


# Copyright
copyright: 'Copyright &copy; 1999-2020 Citrix Systems, Inc. All rights reserved. '

extra_css:
  - 'assets/stylesheets/extra.css'

# Configuration
theme:
  name: null
  custom_dir: devdocs-theme

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: false
  palette:
    primary: white
    accent: blue
  font: false
  favicon: https://www.citrix.com/favicon.ico
  logo: https://developer-docs.citrix.com/_static/Citrix_Logo_Black.png

# Customization
extra:
  social:
    - type: youtube
      link: https://www.youtube.com/channel/UCiOupk9QF6jdk3EDKTHDykA
    - type: github-alt
      link: https://github.com/citrix
    - type: twitter
      link: https://twitter.com/citrixdeveloper
    - type: linkedin
      link: https://www.linkedin.com/company/citrix/

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - meta
  - extra

nav:
- Versions:
  - 1912: https://developer-docs.citrix.com/projects/provisioning-services-sdk/en/1912/
  - 1909: https://developer-docs.citrix.com/projects/provisioning-services-sdk/en/1909/
  - 1906: https://developer-docs.citrix.com/projects/provisioning-services-sdk/en/1906/
  - 1903: https://developer-docs.citrix.com/projects/provisioning-services-sdk/en/1903/
- Introduction: index.md
- Short command list: short-command-list.md
- Commands by object type: commands-by-object-type.md
- MapiReturn returnCode and exceptionType: mapireturn.md
- Questions?: https://discussions.citrix.com/forum/1385-citrix-developer-exchange/